# Generated by Django 5.2.1 on 2025-05-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0003_alter_drinkscategory_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkscategory',
            name='category_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
